ARG BASE_VERSION=latest
FROM fiware/api-umbrella-base:${BASE_VERSION} AS build

COPY test /app/test

WORKDIR /app

ENV INSTALL_TEST_DEPENDENCIES=true

RUN groupadd -r api-umbrella && \
  useradd -r -g api-umbrella -s /sbin/nologin -d /opt/api-umbrella -c "API Umbrella user" api-umbrella

RUN /app/tasks/install-system-build-dependencies
RUN make test-deps

COPY config/test.yml config/test.yml

RUN export PATH="$STAGE_EMBEDDED_DIR/bin:$DEFAULT_PATH"
RUN export BUNDLE_GEMFILE="$SOURCE_DIR/Gemfile"
RUN export BUNDLE_APP_CONFIG="$WORK_DIR/tasks/test-deps/bundle/_persist/.bundle"