ARG BASE_IMAGE=fiware/api-umbrella-base:latest
FROM ${BASE_IMAGE} AS build

COPY test /app/test

WORKDIR /app

ENV INSTALL_TEST_DEPENDENCIES=true

RUN groupadd -r api-umbrella && \
  useradd -r -g api-umbrella -s /sbin/nologin -d /opt/api-umbrella -c "API Umbrella user" api-umbrella

RUN /app/tasks/install-system-build-dependencies
RUN make test-deps

COPY config/test.yml config/test.yml