version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-build
    volumes:
      - .:/app
      - build_cache:/build
    environment:
      HTTP_PORT: 8888
      HTTPS_PORT: 8443
    ports:
      - "8888:8888"
      - "8443:8443"

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  build_cache:
