# Run build tasks, test tasks, and other generic tasks via the go-task tool:
# https://github.com/go-task/task
#
# The primary reason we're using this over something more standard like Make is
# that it provides a simple mechanism to skip tasks based on file checksums.
# This lets us more easily cache and skip steps in the CI and Docker
# development environment (since we only need to cache the build output and
# checksum files, rather than also needing to cache all the intermediate build
# files).
#
# A few general notes on the approach:
#
# - We mostly defer each task to a shell script to do the actual work.
# - For the build process, we use "stamp" files as outputs and also use those
#   within the dependency chain. We use these stamp files so that the
#   checksumming approach properly invalidates the entire chain of dependencies
#   when build files change (whereas just using "deps" in go-task doesn't fully
#   work for multiple levels of dependencies). So, for example, if the
#   libmaxminddb dependency changes, rebuilding it properly cascades and
#   triggers a rebuild of openresty (1st level dependency) and luarocks (2nd
#   level dependency).
# - For colorized output we use the "unbuffer" tool to force color output on
#   some commands, since Task doesn't easily support detecting colorized output
#   (as of the output changes in 2.0.3):
#   https://github.com/go-task/task/issues/136

version: "2"

output: interleaved

tasks:
  deps:geolitecity:
    cmds:
      - ./tasks/deps/geolitecity
    sources:
      - ./tasks/deps/geolitecity
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/geolitecity
    method: none

  deps:libcidr:
    cmds:
      - ./tasks/deps/libcidr
    sources:
      - ./tasks/deps/libcidr
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libcidr
    method: checksum

  deps:libestr:
    cmds:
      - ./tasks/deps/libestr
    sources:
      - ./tasks/deps/libestr
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libestr
    method: checksum

  deps:libfastjson:
    cmds:
      - ./tasks/deps/libfastjson
    sources:
      - ./tasks/deps/libfastjson
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libfastjson
    method: checksum

  deps:libmaxminddb:
    cmds:
      - ./tasks/deps/libmaxminddb
    sources:
      - ./tasks/deps/libmaxminddb
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libmaxminddb
    method: checksum

  deps:luarocks:
    cmds:
      - ./tasks/deps/luarocks
    sources:
      - ./tasks/deps/luarocks
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/luarocks
    method: checksum

  deps:perp:
    cmds:
      - ./tasks/deps/perp
    sources:
      - ./tasks/deps/perp
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/perp
    method: checksum

  deps:runit_svlogd:
    cmds:
      - ./tasks/deps/runit_svlogd
    sources:
      - ./tasks/deps/runit_svlogd
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/runit_svlogd
    method: checksum

  deps:
    cmds:
      - task: deps:libcidr
      - task: deps:luarocks
      - task: deps:perp
      - task: deps:runit_svlogd

  app-deps:lua:argparse:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/argparse
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/argparse
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/argparse
    method: checksum

  app-deps:lua:cmsgpack:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/cmsgpack
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/cmsgpack
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/cmsgpack
    method: checksum

  app-deps:lua:icu-date:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/icu-date
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/icu-date
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/icu-date
    method: checksum

  app-deps:lua:inspect:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/inspect
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/inspect
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/inspect
    method: checksum

  app-deps:lua:libcidr-ffi:
    deps:
      - deps:libcidr
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/libcidr-ffi
    sources:
      - ./build/work/stamp/deps/libcidr
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/libcidr-ffi
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/libcidr-ffi
    method: checksum

  app-deps:lua:luaposix:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/luaposix
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/luaposix
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/luaposix
    method: checksum

  app-deps:lua:luasocket:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/luasocket
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/luasocket
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/luasocket
    method: checksum

  app-deps:lua:lustache:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/lustache
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/lustache
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/lustache
    method: checksum

  app-deps:lua:lyaml:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/lyaml
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/lyaml
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/lyaml
    method: checksum

  app-deps:lua:penlight:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/penlight
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/penlight
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/penlight
    method: checksum

  app-deps:lua:resty-auto-ssl:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-auto-ssl
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-auto-ssl
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-auto-ssl
    method: checksum

  app-deps:lua:resty-http:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-http
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-http
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-http
    method: checksum

  app-deps:lua:resty-jwt:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-jwt
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-jwt
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-jwt
    method: checksum

  app-deps:lua:resty-openssl:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-openssl
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-openssl
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-openssl
    method: checksum

  app-deps:lua:resty-logger-socket:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-logger-socket
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-logger-socket
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-logger-socket
    method: checksum

  app-deps:lua:resty-shcache:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-shcache
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-shcache
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-shcache
    method: checksum

  app-deps:lua:resty-txid:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-txid
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-txid
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-txid
    method: checksum

  app-deps:lua:resty-uuid:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-uuid
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-uuid
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-uuid
    method: checksum


  app-deps:
    cmds:
      - task: app-deps:lua:argparse
      - task: app-deps:lua:cmsgpack
      - task: app-deps:lua:icu-date
      - task: app-deps:lua:inspect
      - task: app-deps:lua:libcidr-ffi
      - task: app-deps:lua:luaposix
      - task: app-deps:lua:luasocket
      - task: app-deps:lua:lustache
      - task: app-deps:lua:lyaml
      - task: app-deps:lua:penlight
      - task: app-deps:lua:resty-auto-ssl
      - task: app-deps:lua:resty-http
      - task: app-deps:lua:resty-jwt
      - task: app-deps:lua:resty-openssl
      - task: app-deps:lua:resty-logger-socket
      - task: app-deps:lua:resty-shcache
      - task: app-deps:lua:resty-txid
      - task: app-deps:lua:resty-uuid

#  app:core:
#    cmds:
#      - ./tasks/app/core
#    sources:
#      - ./tasks/app/core
#      - ./tasks/helpers.sh
#    generates:
#      - ./build/work/stamp/app/core
#    method: checksum

#  app:
#    cmds:
#      - task: app:core

  all:
    cmds:
      - task: deps
      - task: app-deps
#      - task: app

  test-deps:lua:luacheck:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/test-deps/lua/luacheck
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/test-deps/lua/luacheck
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/lua/luacheck
    method: checksum

  test-deps:lua:penlight:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/test-deps/lua/penlight
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/test-deps/lua/penlight
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/lua/penlight
    method: checksum

  test-deps:mailhog:
    cmds:
      - ./tasks/test-deps/mailhog
    sources:
      - ./tasks/test-deps/mailhog
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/mailhog
    method: checksum

  test-deps:eslint:
    cmds:
      - ./tasks/test-deps/eslint

  test-deps:openldap:
    cmds:
      - ./tasks/test-deps/openldap
    sources:
      - ./tasks/test-deps/openldap
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/openldap
    method: checksum

  test-deps:shellcheck:
    cmds:
      - ./tasks/test-deps/shellcheck
    sources:
      - ./tasks/test-deps/shellcheck
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/shellcheck
    method: checksum

  test-deps:unbound:
    cmds:
      - ./tasks/test-deps/unbound
    sources:
      - ./tasks/test-deps/unbound
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/unbound
    method: checksum

  test-deps:
    cmds:
      - task: test-deps:bundle
      - task: test-deps:lua:luacheck
      - task: test-deps:lua:penlight
      - task: test-deps:mailhog
      - task: test-deps:openldap
      - task: test-deps:shellcheck
      - task: test-deps:unbound

  lint:js:
    deps:
      - app-deps:admin-ui:yarn
    cmds:
      - unbuffer ./tasks/lint/js

  lint:lua:
    deps:
      - test-deps:lua:luacheck
    cmds:
      - unbuffer ./tasks/lint/lua

  lint:resty:
    deps:
      - test-deps:lua:penlight
    cmds:
      - unbuffer ./tasks/lint/resty/run

  lint:ruby:
    deps:
      - test-deps:bundle
    cmds:
      - unbuffer ./tasks/lint/ruby

  lint:shell:
    deps:
      - test-deps:shellcheck
    cmds:
      - unbuffer ./tasks/lint/shell

  lint:
    deps:
      - test-deps:eslint
    cmds:
      - task: lint:js
      - task: lint:lua
      - task: lint:resty
      - task: lint:ruby
      - task: lint:shell

  outdated:
    cmds:
      - unbuffer ./tasks/outdated

  clean:dev:
    cmds:
      - ./tasks/clean/dev

  distclean:
    cmds:
      - ./tasks/distclean

  test:
    deps:
      - test-deps
    cmds:
      - unbuffer ./tasks/test/default

  single-test:
    deps:
      - test-deps
    cmds:
      - unbuffer ./tasks/test/single-test

  install:
    cmds:
      - ./tasks/install

  package:
    cmds:
      - ./tasks/package

  install-system-build-dependencies:
    cmds:
      - ./tasks/install-system-build-dependencies

  default:
    cmds:
      - task: all
