#!/usr/bin/env bash

elasticsearch_version="2.4.6"
elasticsearch_hash="c3441bef89cd91206edf3cf3bd5c4b62550e60a9"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$elasticsearch_version.tar.gz" "sha1" "$elasticsearch_hash"
extract_download "elasticsearch-$elasticsearch_version.tar.gz"

mkdir -p "$TEST_INSTALL_PREFIX/elasticsearch"
rsync -a -v --checksum --delete-after "elasticsearch-$elasticsearch_version/" "$TEST_INSTALL_PREFIX/elasticsearch/"
mkdir -p "$TEST_INSTALL_PREFIX/elasticsearch/plugins"

stamp
