name: Pre-Release and Test

on:
  push:

env:
  BASE_IMAGE_NAME: fiware/api-umbrella-base
  TEST_IMAGE_NAME: fiware/api-umbrella-test
  IMAGE_NAME: fiware/api-umbrella

jobs:

  prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: generate temporary tag
        run: echo IMAGE_TAG=$(date +%s) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: Dockerfile-base

      - name: Build test image
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            ${{ env.TEST_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: Dockerfile-test

      - name: Setup test env
        run: |
          docker-compose -f docker/compose/docker-compose.yaml up -d

      - name: Run tests
        run: |
          docker run --network  test-network  ${{ env.TEST_IMAGE_NAME }}:${{ env.IMAGE_TAG }} make test