name: Pre-Release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  BASE_IMAGE_NAME: fiware/api-umbrella-base
  TEST_IMAGE_NAME: fiware/api-umbrella-test
  IMAGE_NAME: fiware/api-umbrella

jobs:

  prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: generate temporary tag
        run: echo IMAGE_TAG=$(date +%s) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base
        run: |
          docker build -f Dockerfile-base -t api-umbrella-base:${{ env.IMAGE_TAG }} .

      - name: Build and push snapshot
        run: |
          docker build -f Dockerfile-build-from-base -t ${{ env.IMAGE_NAME }}:latest --build-arg BASE_IMAGE=api-umbrella-base:${{ env.IMAGE_TAG }} .
          docker push ${{ env.IMAGE_NAME }}:latest