name: Pre-Release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  BASE_IMAGE_NAME: fiware/api-umbrella
  TEST_IMAGE_NAME: fiware/api-umbrella-test
  QUAY_IO_BASE_NAME: quay.io/wi_stefan/api-umbrella

jobs:

  prerelease-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch

      - uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Number
        id: pr_number
        run: echo "::set-output name=nr::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Set version output
        id: out
        run: echo "::set-output name=version::$(echo ${VERSION}-PRE-${{ steps.pr_number.outputs.nr }})"

      - name: generate temporary tag
        run: echo IMAGE_TAG=${{ steps.out.outputs.version }} >> $GITHUB_ENV

  create-images:
    needs: prerelease-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: ["ui", "proxy", "trafficserver", "mora", "rsyslog", "api"]

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log into dockerhub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Log into quay.io
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base
        run: |
          docker build -f docker/files/${{ matrix.image }}/Dockerfile -t ${{env.BASE_IMAGE_NAME}}-${{ matrix.image }}:${{ env.IMAGE_TAG }} .

      - name: Push to dockerhub
        run: |
          docker push ${{env.BASE_IMAGE_NAME}}-${{ matrix.image }}:${{ env.IMAGE_TAG }}

      - name: Push to quay.io
        run: |
          docker tag ${{env.BASE_IMAGE_NAME}}-${{ matrix.image }}:${{ env.IMAGE_TAG }} ${{env.QUAY_IO_BASE_NAME}}-${{ matrix.image }}:${{ env.IMAGE_TAG }}
          docker push ${{env.QUAY_IO_BASE_NAME}}-${{ matrix.image }}:${{ env.IMAGE_TAG }}