name: Pre-Release and Test

on:
  push:

env:
  BASE_IMAGE_NAME: fiware/api-umbrella-base
  TEST_IMAGE_NAME: fiware/api-umbrella-test
  IMAGE_NAME: fiware/api-umbrella

jobs:

  prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: generate temporary tag
        run: echo IMAGE_TAG=$(date +%s) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base
        run: |
          docker build -f Dockerfile-base -t api-umbrella-base:${{ env.IMAGE_TAG }} .

      - name: Build test image
        run: |
          docker build -f Dockerfile-test -t ${{ env.TEST_IMAGE_NAME }}:${{ env.IMAGE_TAG }} --build-arg BASE_IMAGE=api-umbrella-base:${{ env.IMAGE_TAG }} .

      - name: Setup test env
        run: |
          docker-compose -f docker/compose/docker-compose.yaml up -d

      - name: Run tests
        run: |
          docker run -v $(PWD)/test:/app/test/reports -e TEST_TO_RUN=test/proxy/dns/test_custom_server.rb --network  test-network  ${{ env.TEST_IMAGE_NAME }}:${{ env.IMAGE_TAG }} make single-test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: $(PWD)/test