name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Build test image
        run: docker build -f Dockerfile-build -t test-image .

      - name: Lint
        run: docker run test-image make lint

      - name: Run tests on docker
        run: docker run test-image make test