name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - uses: actions/checkout@v2

      - name: Build test image
        run: docker build -f Dockerfile-build --build-arg MAXMIND_LICENSE_KEY_ARG=${{ secrets.MAXMIND_LICENSE_KEY }} -t test-image .

      - name: Run tests on docker
        run: docker run test-image app make test -e